apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-pic-staging

helmCharts:
  - name: base-chart
    repo: oci://ghcr.io/prefeitura-rio/charts
    version: 2.4.2
    releaseName: app-pic-frontend-staging
    valuesInline:
      fullnameOverride: app-pic-frontend

      image:
        repository: ghcr.io/prefeitura-rio/app-pic-frontend
        tag: latest
        pullPolicy: Always

      service:
        port: 80
        containerPort: 3000

      livenessProbe:
        tcpSocket:
          port: http
        initialDelaySeconds: 0
        periodSeconds: 30
        timeoutSeconds: 10
        failureThreshold: 6

      readinessProbe:
        tcpSocket:
          port: http
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3

      startupProbe:
        tcpSocket:
          port: http
        initialDelaySeconds: 0
        periodSeconds: 5
        timeoutSeconds: 5
        failureThreshold: 20

      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 4Gi

      envFrom:
        - secretRef:
            name: frontend-secrets

      autoscaling:
        enabled: false

      replicaCount: 1

      istio:
        enabled: false

      podDisruptionBudget:
        enabled: true
        maxUnavailable: 1

      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: staging.pequenoscariocas.dados.rio
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: app-pic-staging-tls
            hosts:
              - staging.pequenoscariocas.dados.rio

      infisicalSecret:
        enabled: true
        secretName: frontend-secrets
        projectSlug: app-pic-frontend-b-qpn
        envSlug: staging
        kubernetesAuth:
          enabled: true
          identityId: ae19371c-5d95-47e2-a00b-b92a394becb8
          serviceAccountRef:
            name: infisical-auth
            namespace: default

