"""add secretarias_acesso to users

Revision ID: 511d8916ad94
Revises: 82e4a2ad54ff
Create Date: 2026-08-20 17:42:34.239169

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from src.config import env

# revision identifiers, used by Alembic.
revision: str = '511d8916ad94'
down_revision: str | Sequence[str] | None = '82e4a2ad54ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Table name is env-driven (users_staging/users_prod) — same pattern as
    82e4a2ad54ff. Run once per environment, swapping .env in between. The
    autogenerated version also had DROP TABLE ...(_prod)/alembic_version_prod
    statements: false positives from autogenerate diffing the live DB (which
    has both staging and prod tables) against metadata that only knows about
    whichever table name is active in the current .env — removed here.
    """
    op.add_column(
        env.APP_PIC_USERS_TABLE,
        sa.Column(
            "secretarias_acesso",
            sa.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column(env.APP_PIC_USERS_TABLE, "secretarias_acesso")
